kind: "DeploymentConfig"
apiVersion: "v1"
metadata:
  name: "customer-service"
spec:
  template:
    metadata:
      labels:
        name: "customer-service"
    spec:
      containers: 
        - name: "customer-vertx-service"
          image: "andres/consulta-vertx-service:latest"
          ports:
            - containerPort: 8095
              protocol: "TCP"
  replicas: 1 
  triggers: 
    - type: "ConfigChange"
    - type: "ImageChange"
      imageChangeParams:
        automatic: true
        containerNames:
          - "customer-vertx-service"
        from:
          kind: "ImageStreamTag"
          name: "consulta-vertx-service:latest"
  strategy: 
    type: "Rolling"
  paused: false
  revisionHistoryLimit: 2