kind: "DeploymentConfig"
apiVersion: "v1"
metadata:
  name: "consulta-service"
spec:
  template:
    metadata:
      labels:
        name: "consulta-service"
    spec:
      containers: # (1)
        - name: "consulta-vertx-service"
          image: "andres/consulta-vertx-service:latest"
          ports:
            - containerPort: 9000
              protocol: "TCP"
  replicas: 1 # (2)
  triggers: # (3)
    - type: "ConfigChange"
    - type: "ImageChange"
      imageChangeParams:
        automatic: false
        containerNames:
          - "consulta-vertx-service"
        from:
          kind: "ImageStreamTag"
          name: "consulta-vertx-service:latest"
  strategy: # (4)
    type: "Rolling"
  paused: false
  revisionHistoryLimit: 2